---
title: "Untitled"
author: "Harrison Stanton"
date: "2024-07-26"
output: html_document
---

```{r}
library(shiny)
library(tidyverse)
library(dplyr)
library(shinyFeedback)
library(rsconnect)
library(shinymeta)
library(kableExtra)
library(nflfastR)
library(nflreadr)

# trying to put TrapPercentage Code in, see if it works without the CSV
# hvt_tt_long_df <- read_csv("hvt_tt_long_V2.csv")
# hvt_tt_df <- read_csv("hvt_tt_V2.csv")
# teams <- unique(hvt_tt_long_df$team)
# teams <- sort(teams)
# rb_stats_df <- read_csv("RBstats.csv")
# column_names <- c("Total_touches", "Total_HVT", "TRAP", "total_fantasy_points", "total_fantasy_points_exp", "games", "ppg", "xppg", "HVT_perc", "HVT_per_game", "Touches_per_game", "weighted_opps", "wo_per_g")

#All of Trap Percentage Doc
pbp_2023 <- load_pbp(2023)
roster_2023 <- fast_scraper_roster(2023)
snap_counts <- load_snap_counts(2023)
```


```{r}
ff_2023 <- load_ff_opportunity(seasons = most_recent_season(), stat_type = "weekly", model_version = "latest")


roster_2023 <- roster_2023 %>% select(depth_chart_position, full_name, gsis_id, pfr_id, team)
roster_2023 <- roster_2023 %>% filter(depth_chart_position == "RB")



#ff_2023 <- load_ff_opportunity(seasons = most_recent_season(), stat_type = "weekly", model_version = "latest")

ff_2023 <- ff_2023 %>%
  filter(week < 19)

ff_2023 <- ff_2023 %>%
  group_by(player_id) %>%
  mutate(occurrences = n())

ff_2023 <- ff_2023 %>%
  drop_na(player_id) %>%
  group_by(player_id) %>%
  mutate(occurrences = n())


ff_2023 <- ff_2023 %>% rename(gsis_id = player_id)

ff_2023 <- ff_2023 %>% filter(gsis_id %in% roster_2023$gsis_id)

col_to_sum <- c("total_fantasy_points", "total_fantasy_points_exp")


#gonna want to filter this using roster, not position on ff_opportunity... I wanna get rid of fullbacks
#filtered now to get rid of fullbacks
#updating this in NFL app V2
rb_df <- ff_2023 %>%
  group_by(gsis_id) %>%
  summarize_at((col_to_sum), sum)






pbp_2023 <- pbp_2023 %>%
  filter(!(is.na(receiving_yards) & !(is.na(receiver_player_id)))) %>%
  filter(is.na(two_point_conv_result)) %>%
  filter(season_type == "REG")



tt_all <- pbp_2023 %>%
  group_by(receiver_player_id, rusher_player_id) %>%
  filter(is.na(two_point_conv_result)) %>%
  filter(!(is.na(receiving_yards) & !(is.na(receiver_player_id)))) %>%
  summarize(Carries_or_catches = n())


hvt_all <- pbp_2023 %>%
  group_by(receiver_player_id, rusher_player_id) %>%
  filter((!(is.na(rusher_player_id)) & yardline_100 <= 10) | !(is.na(receiver_player_id))) %>%
  summarize(High_value_touches = n())



teams <- roster_2023 %>%
  distinct(team, .keep_all = TRUE) %>%
  pull(team)

new_entries <- c("RB1", "RB2", "RB3")
teams <- c(teams, new_entries)
#print(teams)




tt_all$receiver_player_id <- ifelse(is.na(tt_all$receiver_player_id), tt_all$rusher_player_id, tt_all$receiver_player_id)

tt_all$rusher_player_id <- ifelse(is.na(tt_all$rusher_player_id), tt_all$receiver_player_id, tt_all$rusher_player_id)

tt_all <- tt_all %>%
  group_by(receiver_player_id) %>%
  mutate(Total_touches = sum(Carries_or_catches)) %>%
  ungroup()



tt_all <- tt_all %>%
  distinct(receiver_player_id, .keep_all = TRUE)


tt_all <- tt_all %>%
  select(receiver_player_id, Total_touches)

tt_all <- tt_all %>% rename(gsis_id = receiver_player_id)


#High value touches section

hvt_all$receiver_player_id <- ifelse(is.na(hvt_all$receiver_player_id), hvt_all$rusher_player_id, hvt_all$receiver_player_id)

hvt_all$rusher_player_id <- ifelse(is.na(hvt_all$rusher_player_id), hvt_all$receiver_player_id, hvt_all$rusher_player_id)

hvt_all <- hvt_all %>%
  group_by(receiver_player_id) %>%
  mutate(Total_HVT = sum(High_value_touches)) %>%
  ungroup()



hvt_all <- hvt_all %>%
  distinct(receiver_player_id, .keep_all = TRUE)


hvt_all <- hvt_all %>%
  select(receiver_player_id, Total_HVT)

hvt_all <- hvt_all %>% rename(gsis_id = receiver_player_id)



#High value + total touch data frame
hvt_tt_df <- left_join(roster_2023, tt_all, by = "gsis_id")

hvt_tt_df <- left_join(hvt_tt_df, hvt_all, by = "gsis_id")



hvt_tt_df <- hvt_tt_df %>% filter(!is.na(Total_touches))



hvt_tt_df$Total_HVT <- ifelse(is.na(hvt_tt_df$Total_HVT), 0, hvt_tt_df$Total_HVT)




hvt_tt_df <- hvt_tt_df %>%
  mutate(TRAP = (Total_touches - Total_HVT) / Total_touches)



```

I'm gonna have to do this for all of the 2024 guys who don't show up too

```{r}
#this is comparing guys from roster_2023 to snap_counts to find pfr_ids that didn't automatically show up on roster 2023
#will have to do a section like this in 2024 iteration as well
roster_2023 <- roster_2023 %>%
  mutate(pfr_id = if_else(full_name == "Derrick Gore", "GoreDe00", pfr_id),
         pfr_id = if_else(full_name == "Patrick Taylor", "TaylPa01", pfr_id),
         pfr_id = if_else(full_name == "Tyler Goodson", "GoodTy00", pfr_id),
         pfr_id = if_else(full_name == "Jashaun Corbin", "CorbJa01", pfr_id),
         #left off here
         pfr_id = if_else(full_name == "Deneric Prince", "PrinDe00", pfr_id),
         pfr_id = if_else(full_name == "Chris Brooks", "BrooCh00", pfr_id),
         pfr_id = if_else(full_name == "Xazavian Valladay", "VallXa00", pfr_id))

roster_2023 <- roster_2023 %>%
  filter(!is.na(pfr_id))
```


```{r}
# this will already be in app... gonna have to delete it from one place or the other
snap_counts <- load_snap_counts(
  seasons = most_recent_season(),
  file_type = getOption("nflreadr.prefer", default = "rds")
)

snap_counts <- snap_counts %>%
  filter(position == "RB")




snap_counts <- snap_counts %>%
  filter(game_type == "REG") %>%
  group_by(pfr_player_id) %>%
  mutate(games = n())

games_df <- snap_counts %>%
  select(player, pfr_player_id, games)

games_df <- games_df %>%
  distinct(player, .keep_all = TRUE)
```

```{r}
rb_df <- left_join(rb_df, games_df, by = "gsis_id")
rb_df <- rb_df %>%
  distinct(gsis_id, .keep_all = TRUE)
hvt_tt_df <- left_join(hvt_tt_df, rb_df, by = "gsis_id")



hvt_tt_df <- hvt_tt_df %>%
  mutate(ppg = total_fantasy_points / games,
         xppg = total_fantasy_points_exp / games)

hvt_tt_df <- hvt_tt_df %>%
  mutate(HVT_perc = 1 - TRAP)



hvt_tt_df <- hvt_tt_df %>%
  arrange(desc(total_fantasy_points))



hvt_tt_long_df <- pivot_longer(hvt_tt_df, cols = c(TRAP, HVT_perc),
                               names_to = "Touch_type", values_to = "percentage")

hvt_tt_long_df <- hvt_tt_long_df %>%
  group_by(gsis_id) %>%
  mutate(label_y = cumsum(percentage) - percentage / 2)





# Create bins for ranking
rank_bins <- cut(seq(1, nrow(hvt_tt_long_df)),
                 breaks = c(0, 25, 49, 73, nrow(hvt_tt_long_df)),
                 labels = c("RB1", "RB2", "RB3", "Other"),
                 right = FALSE)

# Add Rank column to the data frame
hvt_tt_long_df$Rank <- as.character(rank_bins)
hvt_tt_long_df$Rank <- ifelse(is.na(hvt_tt_long_df$Rank), "Other", hvt_tt_long_df$Rank)



# Create bins for ranking
rank_bins <- cut(seq(1, nrow(hvt_tt_df)),
                 breaks = c(0, 13, 25, 37, nrow(hvt_tt_df)),
                 labels = c("RB1", "RB2", "RB3", "Other"),
                 right = FALSE)

# Add Rank column to the data frame
hvt_tt_df$Rank <- as.character(rank_bins)
hvt_tt_df$Rank <- ifelse(is.na(hvt_tt_df$Rank), "Other", hvt_tt_df$Rank)





hvt_tt_df <- hvt_tt_df %>%
  mutate(HVT_per_game = Total_HVT / games,
         Touches_per_game = Total_touches/games)


```


need games_df to have gsis_id... think I used roster_2023 last time tbh